# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# Logging
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_ASSERT=y
CONFIG_PRINTK=y

# Shell
CONFIG_SHELL=y
CONFIG_REGULATOR_SHELL=y

# Regulator
CONFIG_REGULATOR=y

# Heap
CONFIG_THREAD_CUSTOM_DATA=y
CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y
CONFIG_DYNAMIC_THREAD_PREFER_ALLOC=y

CONFIG_POLL=y

# Flash
CONFIG_FLASH=y
CONFIG_FLASH_SHELL=y
