# Flash
CONFIG_NORDIC_QSPI_NOR=y
CONFIG_NORDIC_QSPI_NOR_INIT_PRIORITY=90

# QSPI
CONFIG_SPI=y

# I2C
CONFIG_I2C=y

# Charging & Fuel Gauge
CONFIG_CHARGER=y
CONFIG_FUEL_GAUGE=y
CONFIG_FUEL_GAUGE_COMPOSITE=y

